/**
 * generated by Xtext
 */
package br.com.levysiqueira.dsl.textualusecase.validation;

import br.com.levysiqueira.dsl.textualusecase.validation.AbstractTextualUseCaseValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TextualUseCaseValidator extends AbstractTextualUseCaseValidator {
}
