/*
* generated by Xtext
*/
package br.com.levysiqueira.dsl.textualusecase.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextualUseCaseAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("br/com/levysiqueira/dsl/textualusecase/parser/antlr/internal/InternalTextualUseCase.tokens");
	}
}
