/*
* generated by Xtext
*/
package br.com.levysiqueira.dsl.textualusecase.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.com.levysiqueira.dsl.textualusecase.services.TextualUseCaseGrammarAccess;

public class TextualUseCaseParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TextualUseCaseGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.com.levysiqueira.dsl.textualusecase.parser.antlr.internal.InternalTextualUseCaseParser createParser(XtextTokenStream stream) {
		return new br.com.levysiqueira.dsl.textualusecase.parser.antlr.internal.InternalTextualUseCaseParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UseCaseModel";
	}
	
	public TextualUseCaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextualUseCaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
