/*
 * generated by Xtext
 */
package br.com.levysiqueira.dsl.textualusecase.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.com.levysiqueira.dsl.textualusecase.ui.internal.TextualUseCaseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextualUseCaseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextualUseCaseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextualUseCaseActivator.getInstance().getInjector(TextualUseCaseActivator.BR_COM_LEVYSIQUEIRA_DSL_TEXTUALUSECASE_TEXTUALUSECASE);
	}
	
}
