/*
 * generated by Xtext
 */
package br.com.levysiqueira.dsl.textualusecase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextualUseCaseRuntimeModule extends br.com.levysiqueira.dsl.textualusecase.AbstractTextualUseCaseRuntimeModule {

}
