/*
 * generated by Xtext
 */
package br.com.levysiqueira.dsl.textualusecase.ui.contentassist

import br.com.levysiqueira.dsl.textualusecase.ui.contentassist.AbstractTextualUseCaseProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TextualUseCaseProposalProvider extends AbstractTextualUseCaseProposalProvider {
}
