/*
 * generated by Xtext
 */
package br.com.levysiqueira.dsl.textualusecase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextualUseCaseUiModule extends br.com.levysiqueira.dsl.textualusecase.ui.AbstractTextualUseCaseUiModule {
	public TextualUseCaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
