/*
* generated by Xtext
*/
package br.com.levysiqueira.dsl.textualusecase;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TextualUseCaseUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.com.levysiqueira.dsl.textualusecase.ui.internal.TextualUseCaseActivator.getInstance().getInjector("br.com.levysiqueira.dsl.textualusecase.TextualUseCase");
	}
	
}
